# Generated by Django 4.0.4 on 2022-11-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Population_by_countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=256, verbose_name='Год')),
                ('code', models.CharField(max_length=64, verbose_name='Код')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('data', models.BigIntegerField(verbose_name='Люди')),
            ],
        ),
    ]
